# Generated by Django 4.2.3 on 2023-08-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('data', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('data', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CombineDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.date')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.year')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=500)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.combinedate')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='tasks_task_date_id_e96b20_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('task', 'date'), name='unique_task_date', violation_error_message='Task already exist for this date'),
        ),
        migrations.AddConstraint(
            model_name='combinedate',
            constraint=models.UniqueConstraint(fields=('date', 'month', 'year'), name='unique_dates', violation_error_message='Combination of Date already exist'),
        ),
    ]
