# Generated by Django 4.2.3 on 2023-08-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_month_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_date',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_date_id_e96b20_idx',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='combine_date',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['combine_date'], name='tasks_task_combine_6a5f30_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('task', 'combine_date'), name='unique_task_date', violation_error_message='Task already exist for this date'),
        ),
    ]
